(async () => {
const express = require('express'); const cors = require('cors'); const bcrypt = require('bcryptjs'); const jwt = require('jsonwebtoken'); const multer = require('multer'); const path = require('path'); const fs = require('fs');
const db = await require('./db'); const { similarity } = require('./matcher');
const app = express(); const PORT = process.env.PORT || 4000; const SECRET = process.env.JWT_SECRET || 'change-this-secret-before-deployment';
app.use(cors()); app.use(express.json()); app.use('/uploads', express.static(path.join(__dirname,'uploads')));
const uploadDir=path.join(__dirname,'uploads'); if(!fs.existsSync(uploadDir))fs.mkdirSync(uploadDir,{recursive:true});
const storage=multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>cb(null,Date.now()+'-'+Math.random().toString(36).slice(2)+path.extname(file.originalname).slice(0,10))});
const upload=multer({storage,limits:{fileSize:5*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(jpeg|png|webp|gif)$/.test(file.mimetype))});
const tokenFor=u=>jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role},SECRET,{expiresIn:'7d'});
function auth(req,res,next){const h=req.headers.authorization||'';try{req.user=jwt.verify(h.replace(/^Bearer\s+/i,''),SECRET);next()}catch{return res.status(401).json({error:'Please log in to continue.'})}}
function admin(req,res,next){if(req.user?.role!=='admin')return res.status(403).json({error:'Admin access required.'});next()}
function seed(){
 let adminUser=db.prepare('SELECT id FROM Users WHERE email=?').get('admin@lostfound.demo');
 if(!adminUser){const hash=bcrypt.hashSync('Admin@123',10);db.prepare('INSERT INTO Users(name,email,password_hash,role) VALUES(?,?,?,?)').run('Demo Admin','admin@lostfound.demo',hash,'admin')}
 let demo=db.prepare('SELECT id FROM Users WHERE email=?').get('demo@lostfound.demo');
 if(!demo){const hash=bcrypt.hashSync('Demo@123',10);const id=db.prepare('INSERT INTO Users(name,email,password_hash,role) VALUES(?,?,?,?)').run('Demo Student','demo@lostfound.demo',hash,'user').lastInsertRowid;
 const lost=db.prepare('INSERT INTO Lost_Items(user_id,name,category,description,color,item_date,location,image_path) VALUES(?,?,?,?,?,?,?,?)');
 const found=db.prepare('INSERT INTO Found_Items(user_id,name,category,description,color,item_date,location,image_path) VALUES(?,?,?,?,?,?,?,?)');
 lost.run(id,'Blue water bottle','Accessories','Blue stainless steel bottle with a small mountain sticker','Blue','2026-09-28','Central Library','');
 lost.run(id,'Black wireless earbuds','Electronics','Small black earbuds in a charging case','Black','2026-09-25','Student Cafeteria','');
 found.run(id,'Blue metal bottle','Accessories','Blue reusable steel water bottle with sticker on side','Blue','2026-09-29','Central Library entrance','');
 found.run(id,'Earbud case','Electronics','Black wireless earbud case found near tables','Black','2026-09-26','Student Cafeteria','');
 const ls=db.prepare('SELECT * FROM Lost_Items').all(), fs=db.prepare('SELECT * FROM Found_Items').all(); for(const l of ls)for(const f of fs){const m=similarity(l,f);if(m.score>=35)db.prepare('INSERT OR IGNORE INTO Matches(lost_item_id,found_item_id,score,factors) VALUES(?,?,?,?)').run(l.id,f.id,m.score,JSON.stringify(m.factors))}
 db.prepare('INSERT INTO Notifications(user_id,title,message) VALUES(?,?,?)').run(id,'Possible match found','We found a potentially similar blue bottle near the Central Library.');
 }
}
seed();
const toItem=(r,type)=>({...r,type,image_url:r.image_path?'/uploads/'+path.basename(r.image_path):null});
app.get('/api/health',(req,res)=>res.json({ok:true,app:'AI Lost & Found Matcher'}));
app.post('/api/auth/register',async(req,res)=>{try{const {name,email,password}=req.body;if(!name||!email||!password||password.length<8)return res.status(400).json({error:'Name, email and password (8+ characters) are required.'});const hash=await bcrypt.hash(password,10);const id=db.prepare('INSERT INTO Users(name,email,password_hash,role) VALUES(?,?,?,?)').run(name.trim(),email.toLowerCase().trim(),hash,'user').lastInsertRowid;const u=db.prepare('SELECT id,name,email,role FROM Users WHERE id=?').get(id);res.status(201).json({token:tokenFor(u),user:u})}catch(e){res.status(400).json({error:e.message.includes('UNIQUE')?'An account with this email already exists.':'Could not create account.'})}});
app.post('/api/auth/login',async(req,res)=>{const {email,password}=req.body;const u=db.prepare('SELECT * FROM Users WHERE email=?').get(String(email||'').toLowerCase().trim());if(!u||!await bcrypt.compare(password||'',u.password_hash))return res.status(401).json({error:'Email or password is incorrect.'});const safe={id:u.id,name:u.name,email:u.email,role:u.role};res.json({token:tokenFor(safe),user:safe})});
app.get('/api/auth/me',auth,(req,res)=>res.json({user:req.user}));
app.get('/api/items',(req,res)=>{const {q,category,location,status,date}=req.query;let all=[...db.prepare('SELECT * FROM Lost_Items').all().map(r=>toItem(r,'lost')),...db.prepare('SELECT * FROM Found_Items').all().map(r=>toItem(r,'found'))];if(q)all=all.filter(x=>`${x.name} ${x.description}`.toLowerCase().includes(q.toLowerCase()));if(category)all=all.filter(x=>x.category===category);if(location)all=all.filter(x=>x.location.toLowerCase().includes(location.toLowerCase()));if(status&&status!=='all')all=all.filter(x=>x.type===status);if(date)all=all.filter(x=>x.item_date===date);res.json(all.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)))});
app.post('/api/items/:type',auth,upload.single('image'),(req,res)=>{try{const type=req.params.type;if(!['lost','found'].includes(type))return res.status(400).json({error:'Item type must be lost or found.'});const {name,category,description,color,item_date,location}=req.body;if(!name||!category||!description||!item_date||!location)return res.status(400).json({error:'Please complete all required fields.'});const table=type==='lost'?'Lost_Items':'Found_Items';const image=req.file?req.file.path:'';const id=db.prepare(`INSERT INTO ${table}(user_id,name,category,description,color,item_date,location,image_path) VALUES(?,?,?,?,?,?,?,?)`).run(req.user.id,name.trim(),category,description.trim(),color||'',item_date,location.trim(),image).lastInsertRowid;let matches=[];if(type==='lost'){const l=db.prepare('SELECT * FROM Lost_Items WHERE id=?').get(id);for(const f of db.prepare('SELECT * FROM Found_Items WHERE status=\'found\'').all()){const m=similarity(l,f);if(m.score>=30){db.prepare('INSERT OR IGNORE INTO Matches(lost_item_id,found_item_id,score,factors) VALUES(?,?,?,?)').run(l.id,f.id,m.score,JSON.stringify(m.factors));matches.push({...toItem(f,'found'),match_score:m.score,factors:m.factors})}}matches.sort((a,b)=>b.match_score-a.match_score);if(matches.length)db.prepare('INSERT INTO Notifications(user_id,title,message) VALUES(?,?,?)').run(req.user.id,'Potential matches found',`${matches.length} possible found item(s) may match your ${l.name}.`)}else{const f=db.prepare('SELECT * FROM Found_Items WHERE id=?').get(id);for(const l of db.prepare('SELECT * FROM Lost_Items WHERE status=\'lost\'').all()){const m=similarity(l,f);if(m.score>=30){db.prepare('INSERT OR IGNORE INTO Matches(lost_item_id,found_item_id,score,factors) VALUES(?,?,?,?)').run(l.id,f.id,m.score,JSON.stringify(m.factors));const owner=db.prepare('SELECT user_id FROM Lost_Items WHERE id=?').get(l.id);if(owner?.user_id)db.prepare('INSERT INTO Notifications(user_id,title,message) VALUES(?,?,?)').run(owner.user_id,'New found item may match','A newly reported item may match your lost '+l.name+'.')}}}const item=db.prepare(`SELECT * FROM ${table} WHERE id=?`).get(id);res.status(201).json({item:toItem(item,type),matches})}catch(e){console.error(e);res.status(500).json({error:'Could not save this report. Please try again.'})}});
app.get('/api/items/:type/:id',(req,res)=>{const t=req.params.type==='lost'?'Lost_Items':'Found_Items';const row=db.prepare(`SELECT * FROM ${t} WHERE id=?`).get(req.params.id);if(!row)return res.status(404).json({error:'Item not found.'});let result=toItem(row,req.params.type);if(req.params.type==='lost'){result.matches=db.prepare('SELECT m.score as match_score,m.factors,f.* FROM Matches m JOIN Found_Items f ON f.id=m.found_item_id WHERE m.lost_item_id=? ORDER BY m.score DESC').all(row.id).map(x=>({...toItem(x,'found'),match_score:x.match_score,factors:JSON.parse(x.factors||'{}')}))}else{result.matches=db.prepare('SELECT m.score as match_score,m.factors,l.* FROM Matches m JOIN Lost_Items l ON l.id=m.lost_item_id WHERE m.found_item_id=? ORDER BY m.score DESC').all(row.id).map(x=>({...toItem(x,'lost'),match_score:x.match_score,factors:JSON.parse(x.factors||'{}')}))}res.json(result)});
app.get('/api/dashboard',auth,(req,res)=>{const mine=t=>db.prepare(`SELECT * FROM ${t} WHERE user_id=? ORDER BY created_at DESC`).all(req.user.id);const lost=mine('Lost_Items'),found=mine('Found_Items');const matches=db.prepare('SELECT m.*,l.name as lost_name,f.name as found_name,f.location as found_location,f.item_date as found_date,f.image_path as found_image FROM Matches m JOIN Lost_Items l ON l.id=m.lost_item_id JOIN Found_Items f ON f.id=m.found_item_id WHERE l.user_id=? OR f.user_id=? ORDER BY m.score DESC').all(req.user.id,req.user.id);const notifications=db.prepare('SELECT * FROM Notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 8').all(req.user.id);res.json({stats:{lost:lost.length,found:found.length,matches:matches.length,recovered:[...lost,...found].filter(i=>i.status==='recovered').length},recent:[...lost.map(x=>toItem(x,'lost')),...found.map(x=>toItem(x,'found'))].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,6),matches,notifications})});
app.get('/api/notifications',auth,(req,res)=>res.json(db.prepare('SELECT * FROM Notifications WHERE user_id=? ORDER BY created_at DESC').all(req.user.id)));
app.post('/api/notifications/:id/read',auth,(req,res)=>{db.prepare('UPDATE Notifications SET read=1 WHERE id=? AND user_id=?').run(req.params.id,req.user.id);res.json({ok:true})});
app.post('/api/items/:type/:id/recovered',auth,(req,res)=>{const table=req.params.type==='lost'?'Lost_Items':'Found_Items';const r=db.prepare(`UPDATE ${table} SET status='recovered' WHERE id=? AND user_id=?`).run(req.params.id,req.user.id);if(!r.changes)return res.status(404).json({error:'Report not found or not yours.'});res.json({ok:true})});
app.get('/api/admin/overview',auth,admin,(req,res)=>{const count=t=>db.prepare(`SELECT COUNT(*) n FROM ${t}`).get().n;res.json({stats:{users:count('Users'),lost:count('Lost_Items'),found:count('Found_Items'),matches:count('Matches'),recovered:db.prepare("SELECT (SELECT COUNT(*) FROM Lost_Items WHERE status='recovered')+(SELECT COUNT(*) FROM Found_Items WHERE status='recovered') n").get().n,pending:db.prepare("SELECT (SELECT COUNT(*) FROM Lost_Items WHERE status='lost')+(SELECT COUNT(*) FROM Found_Items WHERE status='found') n").get().n},users:db.prepare('SELECT id,name,email,role,created_at FROM Users ORDER BY created_at DESC LIMIT 50').all(),lost:db.prepare('SELECT * FROM Lost_Items ORDER BY created_at DESC').all().map(x=>toItem(x,'lost')),found:db.prepare('SELECT * FROM Found_Items ORDER BY created_at DESC').all().map(x=>toItem(x,'found'))})});
app.patch('/api/admin/items/:type/:id',auth,admin,(req,res)=>{const table=req.params.type==='lost'?'Lost_Items':'Found_Items';const {status}=req.body;if(!['lost','found','recovered','closed'].includes(status))return res.status(400).json({error:'Invalid status.'});const r=db.prepare(`UPDATE ${table} SET status=? WHERE id=?`).run(status,req.params.id);if(!r.changes)return res.status(404).json({error:'Report not found.'});res.json({ok:true})});
app.use((err,req,res,next)=>{if(err instanceof multer.MulterError)return res.status(400).json({error:err.code==='LIMIT_FILE_SIZE'?'Image must be 5 MB or smaller.':'Image upload failed.'});console.error(err);res.status(500).json({error:'Unexpected server error.'})});
app.listen(PORT,()=>console.log(`AI Lost & Found API running at http://localhost:${PORT}`));
})().catch((error) => { console.error('Failed to start AI Lost & Found Matcher:', error); process.exit(1); });
